### ISSUE TITLE
SQL for Test Database

### ISSUE THREAD

**Issue by jabberwik** [StevenRasmussen/EFCore.SqlServer.NodaTime#15]
The unit tests reference a database that is assumed to already exist. Can you publish a script to create those tables so I can ensure the column types are the expected ones when I run the tests myself? Thanks!

**Comment by StevenRasmussen** [comment]
You should be able to uncomment lines 20 and 21 of the file ‘DatabaseTestFixture’ and the database will be created for you. Perhaps I’ll look at updating the readme file to include this.
