### ISSUE TITLE
Are comparison operators supported?

### ISSUE THREAD

**Issue by benmccallum** [StevenRasmussen/EFCore.SqlServer.NodaTime#18]
This is probably a stupid question, but trying to do due diligence before I jump all in on this. Awesome library and will make life so much better!

I can see that SQL functions are support like DateAdd, etc. but I couldn't find anything stating explicitly whether standard operators like `<`, `>`, `==` are translated.

e.g. 
```c#
public class Posts 
{
   public Instant PublishedAt { get; set; }
}

var now = _clock.GetCurrentInstant();
var publishedPosts = db.Posts.Where(p => p.PublishedAt <= now).ToList();
```

Thought I'd ask in case anyone else has the same question and then I can PR a little tweak to the README to state yes/no.

Perhaps the ValueConverters just takes care of all of this, but I've never really used them so not sure.

**Comment by StevenRasmussen** [comment]
Hello!  Yes, all the standard operators are supported ;)
