### ISSUE TITLE
CLR type for Noda Time types

### ISSUE THREAD

**Issue by JonasBRasmussen** [StevenRasmussen/EFCore.SqlServer.NodaTime#20]
When generating EF Core migrations with the Npgsql.EntityFrameworkCore.PostgreSQL.NodaTime library, the CLR type is set to the corresponding Noda Time type, e.g., `Instant` or `LocalDate` in the model snapshot:
```cs
b.Property<Instant>("Created")
    .HasColumnType("timestamp");

b.Property<LocalDate?>("Birthdate")
    .HasColumnType("date");
```
In this library, it is always set to `DateTime`:
```cs
b.Property<DateTime>("Created")
    .HasColumnType("datetime2");

b.Property<DateTime?>("Birthdate")
    .HasColumnType("date");
```
Is there a reason for this? It seems more natural to use the real type instead of always putting `DateTime`.

**Comment by StevenRasmussen** [comment]
That is a bit strange.  I don't think that this library is controlling that aspect at this point.  It is probably just defaulting to the defaults from the core SQL Server provider.  Is it causing issues for you?  Or is it more a cosmetic thing?

**Comment by JonasBRasmussen** [comment]
It's not causing issues - I'm just curious. 🙂

I'm currently transitioning an application from `DateTime` to the Noda Time types, and I noticed that the migrations generated for PostgreSQL are much larger than the corresponding migrations for SQL Server, because the CLR types are changed from `DateTime` to the Noda Time types.

I thought it was something that this library did intentionally, but it makes sense that it is done by the underlying provider.

**Comment by StevenRasmussen** [comment]
There very well could be a hook that we could tie into in order to get it to produce the actual type. I just don't know what to look at in order to find that.  Since it's not causing any issues I probably won't pursue this any further.

**Comment by JonasBRasmussen** [comment]
Perfectly fine. As I said, just curious. 🙂
