### ISSUE TITLE
Support for .NET 6

### ISSUE THREAD

**Issue by maiksch** [StevenRasmussen/EFCore.SqlServer.NodaTime#23]
Hi Steven,

I just upgraded my project to .NET 6 RC1 and now get some errors from this package. 

```
System.TypeLoadException: Method 'GetServiceProviderHashCode' in type 'ExtensionInfo' from assembly 'SimplerSoftware.EntityFrameworkCore.SqlServer.NodaTime, Version=5.0.2.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
   at Microsoft.EntityFrameworkCore.SqlServer.Infrastructure.NodaTimeOptionsExtension.get_Info()
   at Microsoft.EntityFrameworkCore.DbContextOptions.GetHashCode()
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd[TArg](TKey key, Func`3 valueFactory, TArg factoryArgument)
   at Microsoft.EntityFrameworkCore.Internal.ServiceProviderCache.GetOrAdd(IDbContextOptions options, Boolean providerRequired)
   at Microsoft.EntityFrameworkCore.DbContext..ctor(DbContextOptions options)
```

This seems to be due to some breaking changes they talked about here https://github.com/dotnet/efcore/issues/26022. 

Do you plan to support .NET 6 soon?

**Comment by StevenRasmussen** [comment]
I do plan on supporting .Net 6 but TBH haven't looked at what's required to do so.  I'll see if I can't take some time in the next couple of weeks to add support.  Thanks for pointing me to the issue as that will help.

**Comment by StevenRasmussen** [comment]
I have published a release candidate of the package: [https://www.nuget.org/packages/SimplerSoftware.EntityFrameworkCore.SqlServer.NodaTime](https://www.nuget.org/packages/SimplerSoftware.EntityFrameworkCore.SqlServer.NodaTime)

Let me know if you run into any issues.  I will close this issue once I have merged the `dot-net-6` branch into main at the time that EF Core 6 is RTM'd.

**Comment by maiksch** [comment]
I updated to your RC version and everything works again, thank you for resolving this so quick.

**Comment by StevenRasmussen** [comment]
With the .Net 6 RTM today I have merged in the `dot-net-6` branch and published a new NuGet package.
