### ISSUE TITLE
Queries using (DateTime).Date fail to translate

### ISSUE THREAD

**Issue by fordisonharry** [StevenRasmussen/EFCore.SqlServer.NodaTime#25]
Hi,

Thanks a lot for your work on this library.

We are in the process of migrating an existing DbContext where DateTime is still used, and noticed that a specific existing query on an entity that has no NodaTime types fails to translate if the context is configured with NodaTime support, otherwise it translates fine.

It seems the issue is related to the use of `DateTime`'s `Date` property in the LINQ expression.

Here is a simple repro: https://github.com/fordisonharry/EFCore.SqlServer.NodaTime/commit/849667bf4a388cad6f6a34c80138245b4d53ac43

It repros on the .net 6 branch as well.

I will have some more time next weekend to look into it, if it's not immediately obvious to you what the issue is.

Thanks again for the library.

**Comment by StevenRasmussen** [comment]
This is fixed in the `6.0.0` release.

**Comment by fordisonharry** [comment]
Wonderful, thank you!

**Comment by fordisonharry** [comment]
@StevenRasmussen 
Would it be possible to bring that change into a new 5.x release? It would be useful for us (and I assume others) to have that in a version that still targets netstandard, as we may not be able to move everything to 6.0 for a while. Can PR if you wish. Thank you.

**Comment by StevenRasmussen** [comment]
I just published v5.0.3 and v3.1.2 that contains the fix.

**Comment by fordisonharry** [comment]
Thank you : )
