### ISSUE TITLE
Updated to Latest Release and UseNodaTime is Not Working

### ISSUE THREAD

**Issue by kenbo017** [StevenRasmussen/EFCore.SqlServer.NodaTime#33]
I just updated to the latest release and now I'm getting an error.  Is there an update to DbContextOptionsBuilder that I need to install?

SqlServerDbContextOptionsBuilder does not contain a definition for 'UseNodaTime'.

My connection string, which was working before is:

 protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see http://go.microsoft.com/fwlink/?LinkId=723263.
                //optionsBuilder.UseSqlServer("Data Source=KS-PC2\\MSSQLSERVER01;Initial Catalog=kennetix5;Integrated Security=True", x => x.UseNodaTime());
                optionsBuilder.UseSqlServer("Data Source=tcp:76.90.61.172,1433;Initial Catalog=kennetix5;Persist Security Info=True;User ID=ABCD;Password=123456", x => x.UseNodaTime());

**Comment by StevenRasmussen** [comment]
Which version of EF Core are you targeting?  Which version of this package did you just upgrade to?

**Comment by kenbo017** [comment]
Hi Steven,

I'm using EF Core 5.  I'm realizing that I had removed the old version and install the new version 6.0.1 [cid:6eab2c8e-f0a1-4097-af6d-a8b427f3dcad] .

I now see that this version is compatible with >6.0.  How can I install the older version that is compatible with EF Core 5?

Regards,


KS


Ken Schneider
Schneider Sales and Marketing
312 West Hillcrest Blvd.
Inglewood, CA 90301
ph: 310-680-9544
cell: 310-722-8827
e-mail: ***@***.******@***.***>


CONFIDENTIALITY NOTICE. This electronic mail transmission may contain privileged, confidential and/or protected information and is intended only for the review of the party to whom it is addressed. Any unauthorized use or disclosure of the information contained herein may be a violation of federal law. If you have received this transmission in error, please immediately return it to the sender, delete it and destroy it without reading it. Unintended transmission shall not constitute the waiver of the attorney-client or any other privilege.


________________________________

**Comment by StevenRasmussen** [comment]
You can install any version of the package using your NuGet installer of choice (Visual Studio, NuGet CLI etc).  The published versions can be found [here](https://www.nuget.org/packages/SimplerSoftware.EntityFrameworkCore.SqlServer.NodaTime/#versions-body-tab).

**Comment by kenbo017** [comment]
Thanks!

All is good now.


KS


Ken Schneider
Schneider Sales and Marketing
312 West Hillcrest Blvd.
Inglewood, CA 90301
ph: 310-680-9544
cell: 310-722-8827
e-mail: ***@***.******@***.***>


CONFIDENTIALITY NOTICE. This electronic mail transmission may contain privileged, confidential and/or protected information and is intended only for the review of the party to whom it is addressed. Any unauthorized use or disclosure of the information contained herein may be a violation of federal law. If you have received this transmission in error, please immediately return it to the sender, delete it and destroy it without reading it. Unintended transmission shall not constitute the waiver of the attorney-client or any other privilege.


________________________________
