### ISSUE TITLE
Support fot LocalDateTime.Date part

### ISSUE THREAD

**Issue by martinvolek-ext96338** [StevenRasmussen/EFCore.SqlServer.NodaTime#35]
Would it be possible to support `LocalDateTime.Date` part? The behavior should be the same as `DateTime.Date`.

Usage example:

```csharp
// Created property is of LocalDateTime type
Items.Where(x => x.Created.Date == ...)
Items.Where(x => x.Created.Date <= ...)
```

For now (v7.0.0) this fails with: "The LINQ expression '...' could not be translated. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to 'AsEnumerable', 'AsAsyncEnumerable', 'ToList', or 'ToListAsync'. See https://go.microsoft.com/fwlink/?linkid=2101038 for more information."

**Comment by StevenRasmussen** [comment]
@martinvolek-ext96338 - Sorry for the late response.  I have published a new version (7.1) to NuGet that adds support for this.
