### ISSUE TITLE
LocalDateTime being stored as UTC Date in DB

### ISSUE THREAD

**Issue by mweel1** [StevenRasmussen/EFCore.SqlServer.NodaTime#37]
All my dates that are assigned as a LocalDateTime are being stored in the database as 2023-10-27T19:10:18.867Z.

I would expect these to be a local date without any time zone information.

Thank you for the package, any help would be appreciated.

**Comment by StevenRasmussen** [comment]
I'm not sure I understand how you're expecting them to be stored in SQL server.  Are you wanting them to be stored in the local time of the server?  I'm not aware of a way to store them in SQL without any timezone info, either local time or UTC.  I'm also not a  SQL DB expert, so please let me know if you think there's a way to do it.

**Comment by StevenRasmussen** [comment]
Closing due to no response.
