### ISSUE TITLE
Official release with support of .NET 9 / EF Core 9 support

### ISSUE THREAD

**Issue by thomasbach-dk** [StevenRasmussen/EFCore.SqlServer.NodaTime#42]
Hi,

When are you planning to release a new official package of 9.0.0-rc.1.24451.1 with official support of .NET 9 / EF Core 9?

Thanks in advance!

Best regards,
Thomas

**Comment by StevenRasmussen** [comment]
Hi Thomas. I just published the NuGet package. Reference #43
