### ISSUE TITLE
Support net standard 2.0

### ISSUE THREAD

**Issue by nhedlund** [StevenRasmussen/EFCore.SqlServer.NodaTime#8]
Can you change the project from net standard 2.1 to 2.0?

This would greatly increase the usage of the library, especially for the unfortunate souls that have to support NET Framework projects a little while longer.

You have 3 dependencies to this nuget, and all dependencies supports net standard 2.0 so there is no reason for this nuget to require 2.1.

I cloned the repo and changed it to 2.0 and it builds fine and the tests runs ok.

Please change the target framework in the main csproj to netstandard2.0 and release a new version :)

**Comment by StevenRasmussen** [comment]
@nhedlund - Thanks for the suggestion! Not sure why I had this targeting 2.1. Version 1.3.2 supports 2.0 now... should be published here shortly.

**Comment by nhedlund** [comment]
That was fast! Thanks! 👍
